/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 gamescene.glb --transform 
Files: gamescene.glb [8.2MB] > C:\Users\bellotb\OneDrive - ILIAS Solutions NV\Documents\bachelor-proef\bachelor-endproject\public\assets\game\gamescene-transformed.glb [551.49KB] (93%)
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "./assets/game/gamescene-transformed.glb"
  );
  const { actions } = useAnimations(animations, group);

  // Function to recursively traverse through the scene and set castShadow to true for all meshes
  const enableShadows = (obj) => {
    if (obj && obj.isMesh) {
      obj.castShadow = true;
    }
    if (obj && obj.children) {
      obj.children.forEach((child) => {
        enableShadows(child);
      });
    }
  };

  // Call the function to enable shadows for all meshes in the scene
  enableShadows(group.current);

  return (
    <group
      position={[0, 5, 0]}
      scale={[10, 10, 10]}
      ref={group}
      {...props}
      dispose={null}
    >
      <group name="Scene">
        <group name="Fan" position={[0.647, 0.311, -1.682]} scale={0.01}>
          <group name="eje" position={[0, 46.481, 0]}>
            <group name="polySurface10" position={[0, -47.236, 0]}>
              <mesh
                name="polySurface10_Fan1_0"
                geometry={nodes.polySurface10_Fan1_0.geometry}
                material={materials.PaletteMaterial002}
              />
            </group>
            <group name="polySurface3" position={[0, -47.236, 0]}>
              <mesh
                name="polySurface3_Fan2_0"
                geometry={nodes.polySurface3_Fan2_0.geometry}
                material={materials.PaletteMaterial002}
              />
              <mesh
                name="polySurface3_Fan_light_0"
                geometry={nodes.polySurface3_Fan_light_0.geometry}
                material={materials.PaletteMaterial003}
              />
            </group>
            <group name="polySurface7" position={[0, -47.236, 0]}>
              <mesh
                name="polySurface7_Fan1_0"
                geometry={nodes.polySurface7_Fan1_0.geometry}
                material={materials.PaletteMaterial002}
              />
            </group>
            <group name="polySurface8" position={[0, -47.236, 0]}>
              <mesh
                name="polySurface8_Fan1_0"
                geometry={nodes.polySurface8_Fan1_0.geometry}
                material={materials.PaletteMaterial002}
              />
            </group>
            <group name="polySurface9" position={[0, -47.236, 0]}>
              <mesh
                name="polySurface9_Fan1_0"
                geometry={nodes.polySurface9_Fan1_0.geometry}
                material={materials.PaletteMaterial002}
              />
            </group>
          </group>
          <group name="nurbsCircle1" position={[231.805, 49.038, -82.967]} />
        </group>
        <group name="Fan3" position={[-0.269, 0.311, -1.774]} scale={0.01}>
          <group name="eje001" position={[0, 46.481, 0]}>
            <group name="polySurface10001" position={[0, -46.941, 0]}>
              <mesh
                name="polySurface10_Fan1_0001"
                geometry={nodes.polySurface10_Fan1_0001.geometry}
                material={materials.PaletteMaterial002}
              />
            </group>
            <group name="polySurface3001" position={[0, -44.738, 0]}>
              <mesh
                name="polySurface3_Fan2_0001"
                geometry={nodes.polySurface3_Fan2_0001.geometry}
                material={materials.PaletteMaterial002}
              />
              <mesh
                name="polySurface3_Fan_light_0001"
                geometry={nodes.polySurface3_Fan_light_0001.geometry}
                material={materials.PaletteMaterial003}
              />
            </group>
            <group name="polySurface7001" position={[0, -46.941, 0]}>
              <mesh
                name="polySurface7_Fan1_0001"
                geometry={nodes.polySurface7_Fan1_0001.geometry}
                material={materials.PaletteMaterial002}
              />
            </group>
            <group name="polySurface8001" position={[0, -46.941, 0]}>
              <mesh
                name="polySurface8_Fan1_0001"
                geometry={nodes.polySurface8_Fan1_0001.geometry}
                material={materials.PaletteMaterial002}
              />
            </group>
            <group name="polySurface9001" position={[0, -46.941, 0]}>
              <mesh
                name="polySurface9_Fan1_0001"
                geometry={nodes.polySurface9_Fan1_0001.geometry}
                material={materials.PaletteMaterial002}
              />
            </group>
          </group>
          <group name="nurbsCircle1001" position={[651.428, 49.038, 231.75]} />
        </group>
        <group name="Fan3002" position={[0.646, 0.311, -2.555]} scale={0.01}>
          <group name="eje002" position={[0, 46.481, 0]}>
            <group name="polySurface10002" position={[0, -46.941, 0]}>
              <mesh
                name="polySurface10_Fan1_0002"
                geometry={nodes.polySurface10_Fan1_0002.geometry}
                material={materials.PaletteMaterial002}
              />
            </group>
            <group name="polySurface3002" position={[0, -44.738, 0]}>
              <mesh
                name="polySurface3_Fan2_0002"
                geometry={nodes.polySurface3_Fan2_0002.geometry}
                material={materials.PaletteMaterial002}
              />
              <mesh
                name="polySurface3_Fan_light_0002"
                geometry={nodes.polySurface3_Fan_light_0002.geometry}
                material={materials.PaletteMaterial003}
              />
            </group>
            <group name="polySurface7002" position={[0, -46.941, 0]}>
              <mesh
                name="polySurface7_Fan1_0002"
                geometry={nodes.polySurface7_Fan1_0002.geometry}
                material={materials.PaletteMaterial002}
              />
            </group>
            <group name="polySurface8002" position={[0, -46.941, 0]}>
              <mesh
                name="polySurface8_Fan1_0002"
                geometry={nodes.polySurface8_Fan1_0002.geometry}
                material={materials.PaletteMaterial002}
              />
            </group>
            <group name="polySurface9002" position={[0, -46.941, 0]}>
              <mesh
                name="polySurface9_Fan1_0002"
                geometry={nodes.polySurface9_Fan1_0002.geometry}
                material={materials.PaletteMaterial002}
              />
            </group>
          </group>
        </group>
        <group name="Fan3003" position={[0.646, 0.311, -2.555]} scale={0.01}>
          <group name="eje003" position={[0, 46.481, 0]}>
            <group name="polySurface10003" position={[0, -46.941, 0]}>
              <mesh
                name="polySurface10_Fan1_0003"
                geometry={nodes.polySurface10_Fan1_0003.geometry}
                material={materials.PaletteMaterial002}
              />
            </group>
            <group name="polySurface3003" position={[0, -44.738, 0]}>
              <mesh
                name="polySurface3_Fan2_0003"
                geometry={nodes.polySurface3_Fan2_0003.geometry}
                material={materials.PaletteMaterial002}
              />
              <mesh
                name="polySurface3_Fan_light_0003"
                geometry={nodes.polySurface3_Fan_light_0003.geometry}
                material={materials.PaletteMaterial003}
              />
            </group>
            <group name="polySurface7003" position={[0, -46.941, 0]}>
              <mesh
                name="polySurface7_Fan1_0003"
                geometry={nodes.polySurface7_Fan1_0003.geometry}
                material={materials.PaletteMaterial002}
              />
            </group>
            <group name="polySurface8003" position={[0, -46.941, 0]}>
              <mesh
                name="polySurface8_Fan1_0003"
                geometry={nodes.polySurface8_Fan1_0003.geometry}
                material={materials.PaletteMaterial002}
              />
            </group>
            <group name="polySurface9003" position={[0, -46.941, 0]}>
              <mesh
                name="polySurface9_Fan1_0003"
                geometry={nodes.polySurface9_Fan1_0003.geometry}
                material={materials.PaletteMaterial002}
              />
            </group>
          </group>
        </group>
        <group name="Fan004" position={[0.647, 0.311, -1.682]} scale={0.01}>
          <group name="eje004" position={[0, 46.481, 0]} />
        </group>
        <group name="Fan005" position={[0.647, 0.311, -1.682]} scale={0.01}>
          <group name="eje005" position={[0, 46.481, 0]} />
        </group>
        <group name="Fan006" position={[0.647, 0.311, -1.682]} scale={0.01}>
          <group name="eje006" position={[0, 46.481, 0]} />
        </group>
        <group name="Fan3004" position={[-0.248, 0.311, -2.555]} scale={0.01}>
          <group name="eje007" position={[0, 46.481, 0]}>
            <group name="polySurface10007" position={[0, -46.941, 0]}>
              <mesh
                name="polySurface10_Fan1_0004"
                geometry={nodes.polySurface10_Fan1_0004.geometry}
                material={materials.PaletteMaterial002}
              />
            </group>
            <group name="polySurface3007" position={[0, -44.738, 0]}>
              <mesh
                name="polySurface3_Fan2_0004"
                geometry={nodes.polySurface3_Fan2_0004.geometry}
                material={materials.PaletteMaterial002}
              />
              <mesh
                name="polySurface3_Fan_light_0004"
                geometry={nodes.polySurface3_Fan_light_0004.geometry}
                material={materials.PaletteMaterial003}
              />
            </group>
            <group name="polySurface7007" position={[0, -46.941, 0]}>
              <mesh
                name="polySurface7_Fan1_0004"
                geometry={nodes.polySurface7_Fan1_0004.geometry}
                material={materials.PaletteMaterial002}
              />
            </group>
            <group name="polySurface8007" position={[0, -46.941, 0]}>
              <mesh
                name="polySurface8_Fan1_0004"
                geometry={nodes.polySurface8_Fan1_0004.geometry}
                material={materials.PaletteMaterial002}
              />
            </group>
            <group name="polySurface9007" position={[0, -46.941, 0]}>
              <mesh
                name="polySurface9_Fan1_0004"
                geometry={nodes.polySurface9_Fan1_0004.geometry}
                material={materials.PaletteMaterial002}
              />
            </group>
          </group>
        </group>
        <group name="Fan3005" position={[-0.248, 0.311, -2.555]} scale={0.01}>
          <group name="eje008" position={[0, 46.481, 0]}>
            <group name="polySurface10008" position={[0, -46.941, 0]}>
              <mesh
                name="polySurface10_Fan1_0005"
                geometry={nodes.polySurface10_Fan1_0005.geometry}
                material={materials.PaletteMaterial002}
              />
            </group>
            <group name="polySurface3008" position={[0, -44.738, 0]}>
              <mesh
                name="polySurface3_Fan2_0005"
                geometry={nodes.polySurface3_Fan2_0005.geometry}
                material={materials.PaletteMaterial002}
              />
              <mesh
                name="polySurface3_Fan_light_0005"
                geometry={nodes.polySurface3_Fan_light_0005.geometry}
                material={materials.PaletteMaterial003}
              />
            </group>
            <group name="polySurface7008" position={[0, -46.941, 0]}>
              <mesh
                name="polySurface7_Fan1_0005"
                geometry={nodes.polySurface7_Fan1_0005.geometry}
                material={materials.PaletteMaterial002}
              />
            </group>
            <group name="polySurface8008" position={[0, -46.941, 0]}>
              <mesh
                name="polySurface8_Fan1_0005"
                geometry={nodes.polySurface8_Fan1_0005.geometry}
                material={materials.PaletteMaterial002}
              />
            </group>
            <group name="polySurface9008" position={[0, -46.941, 0]}>
              <mesh
                name="polySurface9_Fan1_0005"
                geometry={nodes.polySurface9_Fan1_0005.geometry}
                material={materials.PaletteMaterial002}
              />
            </group>
          </group>
        </group>
        <mesh
          name="group1872417371"
          geometry={nodes.group1872417371.geometry}
          material={materials.PaletteMaterial001}
          position={[-2.913, 0.4, -0.046]}
          rotation={[-Math.PI / 2, -1.492, -Math.PI / 2]}
          scale={[1.908, 2.1, 1.011]}
        />
        <mesh
          name="pCube17_Louver1_0003"
          geometry={nodes.pCube17_Louver1_0003.geometry}
          material={materials.PaletteMaterial002}
          position={[-134.534, 0, 0]}
        />
        <mesh
          name="Cube001"
          geometry={nodes.Cube001.geometry}
          material={nodes.Cube001.material}
          position={[-4, 0.461, -5]}
          scale={[1, 0.37, 1]}
        />
        <mesh
          name="building_E"
          geometry={nodes.building_E.geometry}
          material={materials.citybits_texture}
          position={[-2, 0, 2]}
          scale={100}
        />
        <mesh
          name="StreetLights"
          geometry={nodes.StreetLights.geometry}
          material={materials["Atlas.053"]}
          position={[-0.322, 0, -1.114]}
          scale={20}
        />
        <mesh
          name="Material2106"
          geometry={nodes.Material2106.geometry}
          material={materials["Wood_Cherry_Original_3.002"]}
          position={[0.207, 0.1, -2.486]}
          rotation={[-Math.PI / 2, 0, -2.094]}
          scale={0.007}
        />
        <mesh
          name="Material2088"
          geometry={nodes.Material2088.geometry}
          material={materials["Stone_Vein_Gray.002"]}
          position={[0.169, 0.294, -2.218]}
          rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
          scale={[-0.007, 0.007, 0.007]}
        />
        <mesh
          name="Screen_Screen1_0001"
          geometry={nodes.Screen_Screen1_0001.geometry}
          material={materials.PaletteMaterial004}
          position={[-0.435, 0, -3.869]}
          scale={[0.045, 0.021, 0.021]}
        />
        <mesh
          name="building_E001"
          geometry={nodes.building_E001.geometry}
          material={materials["citybits_texture.002"]}
          position={[2, 0, 2]}
          scale={100}
        />
        <mesh
          name="bottle_1_bottle_label_blinn_0"
          geometry={nodes.bottle_1_bottle_label_blinn_0.geometry}
          material={materials.bottle_label_blinn}
          position={[-0.728, 0.221, -2.376]}
          rotation={[0, Math.PI / 2, 0]}
          scale={0.01}
        />
        <mesh
          name="counter_black_metal_blinn_0"
          geometry={nodes.counter_black_metal_blinn_0.geometry}
          material={materials.black_metal_blinn}
          position={[-0.728, 0.221, -2.376]}
          rotation={[0, Math.PI / 2, 0]}
          scale={0.01}
        />
        <mesh
          name="shelf_metal_blinn_0"
          geometry={nodes.shelf_metal_blinn_0.geometry}
          material={materials.metal_blinn}
          position={[-0.718, 0.221, -2.376]}
          rotation={[0, Math.PI / 2, 0]}
          scale={0.01}
        />
        <mesh
          name="stool_1_leather_blinn_0"
          geometry={nodes.stool_1_leather_blinn_0.geometry}
          material={materials.leather_blinn}
          position={[-0.728, 0.221, -2.376]}
          rotation={[0, Math.PI / 2, 0]}
          scale={0.01}
        />
        <mesh
          name="Biere_M_1002_0"
          geometry={nodes.Biere_M_1002_0.geometry}
          material={materials.M_1002}
          position={[0.525, 0.328, -1.863]}
          scale={0.001}
        />
        <mesh
          name="Pied_poker_low_01_M_1001_0"
          geometry={nodes.Pied_poker_low_01_M_1001_0.geometry}
          material={materials.M_1001}
          position={[0.61, 0.11, -1.722]}
          scale={0.002}
        />
      </group>
    </group>
  );
}

useGLTF.preload("./assets/game/gamescene-transformed.glb");
