/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 office.gltf --transform 
Files: office.gltf [131.6KB] > D:\b\Bachelor_3\finalwork\Web\bachelor-proef\bachelor-endproject\public\assets\office\office-transformed.glb [891.22KB] (-577%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Office(props) {
  const { nodes, materials } = useGLTF('./assets/office/office-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Door.geometry} material={materials.lambert3SG} position={[-4, -1, 3.894]} scale={0.013} />
      <mesh geometry={nodes.Ashtray.geometry} material={materials.PaletteMaterial001} position={[-0.765, 0.565, -1.202]} scale={0.173} />
      <mesh geometry={nodes.Blackboard_Q.geometry} material={materials.phong1SG} position={[0.278, 1.703, 3.925]} rotation={[Math.PI, -0.014, Math.PI]} scale={4.159} />
      <mesh geometry={nodes.Cube001.geometry} material={materials.PaletteMaterial002} position={[0, 1.489, 0]} rotation={[0, 0, Math.PI / 2]} scale={[2.52, 6, 4]} />
      <mesh geometry={nodes.group399781975.geometry} material={materials.PaletteMaterial003} position={[10, 0, 0]} />
      <mesh geometry={nodes.defaultMaterial001.geometry} material={materials.bureau} position={[0.16, 0, -1.3]} rotation={[-Math.PI, 0, -Math.PI]} scale={1.357} />
      <mesh geometry={nodes.Low_Back_Chair_0.geometry} material={materials.Chair} position={[0.024, 0.102, -3.016]} rotation={[-Math.PI / 2, 0, 3.13]} scale={0.029} />
      <mesh geometry={nodes.Selector_Main_0.geometry} material={materials.Main} position={[3.762, 0.221, 2.986]} rotation={[-Math.PI / 2, 0, -2.384]} scale={1.646} />
      <mesh geometry={nodes.TV_Screen_0.geometry} material={materials.Screen} position={[4.47, -0.95, 2.81]} rotation={[-Math.PI / 2, 0, -2.384]} scale={1.646} />
      <mesh geometry={nodes.Record_Player_M_Archaeologist_Record_Player_0.geometry} material={materials.M_Archaeologist_Record_Player} position={[-5.461, 0.346, -0.035]} rotation={[0, 1.396, 0]} scale={0.324} />
      <mesh geometry={nodes.Object_2002.geometry} material={materials['Scene_-_Root']} position={[1.103, 0.537, -1.355]} rotation={[-Math.PI / 2, 0, -2.967]} scale={0.032} />
    </group>
  )
}

useGLTF.preload("./assets/office/office-transformed.glb");
