/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.gltf --transform 
Files: scene.gltf [48.67KB] > D:\b\Bachelor_3\finalwork\Web\bachelor-proef\bachelor-endproject\public\assets\testroom\scene-transformed.glb [504.67KB] (-937%)
Author: Fede (https://sketchfab.com/fedemergent)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/medieval-isometric-room-low-poly-02808aa7476e469bb4e74cd159661423
Title: Medieval isometric Room - Low Poly
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Testroom(props) {
  const { nodes, materials } = useGLTF(
    "./assets/testroom/scene-transformed.glb"
  );
  return (
    <group {...props} position={(0, 0, 0)} scale={1}>
   
      <mesh
        geometry={nodes.Object_3.geometry}
        material={materials.Turril_Madera}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.023}
      />
      <mesh
        geometry={nodes.Object_11.geometry}
        material={materials.Madera}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.023}
      />
      <mesh
        geometry={nodes.Object_12.geometry}
        material={materials.PaletteMaterial002}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.023}
      />
      <mesh
        geometry={nodes.Object_23.geometry}
        material={materials.PaletteMaterial003}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.023}
      />
      <mesh
        geometry={nodes.Object_25.geometry}
        material={materials.Baul_Madera}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.023}
      />
      <mesh
        geometry={nodes.Object_26.geometry}
        material={materials.Puerta_Madera}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.023}
      />
      <mesh
        geometry={nodes.Object_28.geometry}
        material={materials.PaletteMaterial004}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.023}
      />
      <mesh
        geometry={nodes.Object_30.geometry}
        material={materials.PaletteMaterial005}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.023}
      />
    </group>
  );
}

useGLTF.preload("./assets/testroom/scene-transformed.glb");
